import AIToolUsage from '../models/AIToolUsage.js';
import SavedContent from '../models/SavedContent.js';

/**
 * Get user's usage history
 */
export const getUsageHistory = async (req, res) => {
  try {
    const { toolName, limit = 10, page = 1 } = req.query;
    const userId = req.userId;

    const query = { userId };
    if (toolName) query.toolName = toolName;

    const skip = (page - 1) * limit;

    const history = await AIToolUsage.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit));

    const total = await AIToolUsage.countDocuments(query);

    res.json({
      success: true,
      data: history,
      pagination: {
        total,
        page: parseInt(page),
        limit: parseInt(limit),
        pages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Failed to fetch usage history',
      error: error.message,
    });
  }
};

/**
 * Save content generated by AI tool
 */
export const saveContent = async (req, res) => {
  try {
    const { toolName, title, content, metadata, tags } = req.body;
    const userId = req.userId;

    const savedContent = new SavedContent({
      userId,
      toolName,
      title,
      content,
      metadata,
      tags,
    });

    await savedContent.save();

    res.status(201).json({
      success: true,
      message: 'Content saved successfully',
      data: savedContent,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Failed to save content',
      error: error.message,
    });
  }
};

/**
 * Get saved content by user
 */
export const getSavedContent = async (req, res) => {
  try {
    const { toolName, isFavorite, limit = 10, page = 1 } = req.query;
    const userId = req.userId;

    const query = { userId };
    if (toolName) query.toolName = toolName;
    if (isFavorite === 'true') query.isFavorite = true;

    const skip = (page - 1) * limit;

    const content = await SavedContent.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit));

    const total = await SavedContent.countDocuments(query);

    res.json({
      success: true,
      data: content,
      pagination: {
        total,
        page: parseInt(page),
        limit: parseInt(limit),
        pages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Failed to fetch saved content',
      error: error.message,
    });
  }
};

/**
 * Update saved content
 */
export const updateSavedContent = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, content, isFavorite, tags } = req.body;
    const userId = req.userId;

    const savedContent = await SavedContent.findOneAndUpdate(
      { _id: id, userId },
      { title, content, isFavorite, tags },
      { new: true, runValidators: true }
    );

    if (!savedContent) {
      return res.status(404).json({
        success: false,
        message: 'Content not found',
      });
    }

    res.json({
      success: true,
      message: 'Content updated successfully',
      data: savedContent,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Failed to update content',
      error: error.message,
    });
  }
};

/**
 * Delete saved content
 */
export const deleteSavedContent = async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.userId;

    const savedContent = await SavedContent.findOneAndDelete({ _id: id, userId });

    if (!savedContent) {
      return res.status(404).json({
        success: false,
        message: 'Content not found',
      });
    }

    res.json({
      success: true,
      message: 'Content deleted successfully',
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Failed to delete content',
      error: error.message,
    });
  }
};
